<a href="https://colab.research.google.com/github/jose4747/Data-science-1/blob/main/Heart_Disease_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
path='/content/drive/MyDrive/Colab Notebooks/heart.data.csv'
import pandas as pd
df = pd.read_csv(path)
df

     Unnamed: 0     biking    smoking  heart.disease
0             1  30.801246  10.896608      11.769423
1             2  65.129215   2.219563       2.854081
2             3   1.959665  17.588331      17.177803
3             4  44.800196   2.802559       6.816647
4             5  69.428454  15.974505       4.062224
..          ...        ...        ...            ...
493         494  47.660440  27.562464      11.294392
494         495  45.097203  21.385620       9.616762
495         496   8.279743   6.423720      13.495168
496         497  42.345863  20.741328      10.115865
497         498  30.774254  23.610175      11.843556

[498 rows x 4 columns]

In [ ]:
from sklearn.model_selection import train_test_split
x = df['smoking']
y = df['heart.disease']
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size = 0.75, shuffle = True)
from sklearn.linear_model import LinearRegression
print(x_train.shape)
print(x_test.shape)

(373,)
(125,)

In [ ]:
import numpy as np
x_train=np.array(x_train).reshape(-1,1)
y_train=np.array(y_train).reshape(-1,1)

model=LinearRegression()
model. fit(x_train,y_train)

print (model. coef_)
print(model.intercept_)

[[0.12240279]]
[8.12514388]

In [ ]:
y_test=np.array(y_test).reshape(-1,1)
y_pred=model.predict(y_test)
print(y_pred)

[[ 8.95896918]
 [ 9.07955511]
 [ 9.7952513 ]
 [ 9.79902428]
 [ 9.69172658]
 [ 8.27577016]
 [ 9.04800434]
 [ 9.37153302]
 [ 9.19853711]
 [ 9.5619661 ]
 [ 9.43170161]
 [ 9.04461735]
 [ 9.88041857]
 [ 9.05496139]
 [ 8.19435958]
 [ 8.48267852]
 [ 8.33079823]
 [ 8.57295598]
 [ 8.89860026]
 [ 9.00964359]
 [ 9.86662278]
 [10.13919904]
 [10.46168778]
 [ 8.35036349]
 [ 8.69564753]
 [ 8.46467205]
 [ 9.50785724]
 [10.33269843]
 [ 8.63626248]
 [ 8.528898  ]
 [10.10429107]
 [10.45915426]
 [ 8.0653218 ]
 [10.04901912]
 [ 8.62081821]
 [ 9.35248804]
 [ 9.08029611]
 [ 9.21292531]
 [ 9.58011029]
 [ 8.68507221]
 [ 7.73362769]
 [10.12640282]
 [ 8.62415752]
 [ 9.34812504]
 [ 8.64181251]
 [ 9.65246409]
 [10.45391915]
 [ 9.60664749]
 [10.31730964]
 [ 8.65172533]
 [ 9.33604563]
 [10.26354262]
 [ 9.60923715]
 [ 9.04362656]
 [ 9.09963883]
 [ 8.85572202]
 [ 8.53986189]
 [ 9.62081615]
 [ 9.90314878]
 [ 9.19903866]
 [ 8.68923934]
 [ 9.38877635]
 [ 9.32914973]
 [ 8.38972097]
 [ 8.24017706]
 [ 9.7357206 ]
 [ 8.94970627]
 [ 9.9163828 ]
 [ 9.70042402]
 [ 9.6562877 ]
 [ 7.92903364]
 [10.73513992]
 [ 9.32745675]
 [ 9.40021397]
 [ 9.44112317]
 [ 9.47546387]
 [ 8.0024548 ]
 [10.12494202]
 [ 8.97418092]
 [ 9.24020199]
 [ 9.86722873]
 [10.27317546]
 [ 9.25297385]
 [ 9.67924974]
 [ 8.04601943]
 [ 9.17462539]
 [ 8.38863052]
 [ 9.74688199]
 [ 9.26504675]
 [ 9.39014232]
 [ 9.07591285]
 [ 7.67323891]
 [ 8.74100119]
 [10.30980488]
 [ 9.81585684]
 [ 9.7038799 ]
 [ 9.15545014]
 [ 8.74607266]
 [ 8.42317643]
 [ 8.42038941]
 [10.46142924]
 [ 8.76126014]
 [ 8.58454366]
 [ 9.08887152]
 [10.16031766]
 [ 9.36158521]
 [10.69355605]
 [ 9.31150699]
 [ 9.31536735]
 [ 8.39367337]
 [ 9.6910908 ]
 [10.2088312 ]
 [ 8.00247455]
 [ 8.92273415]
 [10.08575159]
 [ 8.88490295]
 [ 8.58080623]
 [ 9.14150388]
 [ 9.74566748]
 [ 8.94322707]
 [10.02427322]
 [ 7.91111178]
 [ 9.64409805]
 [ 9.38254113]
 [ 8.60827881]]

In [ ]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
import math

print('Mean absolute error:', mean_absolute_error(y_test, y_pred))

print("Mean squared error:", mean_squared_error(y_test, y_pred))
print('variance score:',r2_score(y_test, y_pred))

print('Root Mean Squared Error:',math.sqrt(mean_squared_error(y_test, y_pred)))

Mean absolute error: 3.3535687557311786
Mean squared error: 16.584980665046483
variance score: 0.16772135793824272
Root Mean Squared Error: 4.072466164997136