<a href="https://colab.research.google.com/github/JohnHenin/Data-science/blob/main/Metric.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
path='/content/heart.data.csv'
#For temporary storage directly upload the file on colab
import pandas as pd

#Can write the path directly as well
df = pd.read_csv(path)
df

     Unnamed: 0     biking    smoking  heart.disease
0             1  30.801246  10.896608      11.769423
1             2  65.129215   2.219563       2.854081
2             3   1.959665  17.588331      17.177803
3             4  44.800196   2.802559       6.816647
4             5  69.428454  15.974505       4.062224
..          ...        ...        ...            ...
493         494  47.660440  27.562464      11.294392
494         495  45.097203  21.385620       9.616762
495         496   8.279743   6.423720      13.495168
496         497  42.345863  20.741328      10.115865
497         498  30.774254  23.610175      11.843556

[498 rows x 4 columns]

In [3]:
from sklearn.model_selection import train_test_split
x = df['smoking']
y = df['heart.disease']
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size = 0.75, shuffle = True)
from sklearn.linear_model import LinearRegression
print(x_train.shape)
print(x_test.shape)

(373,)
(125,)

In [4]:
import numpy as np
x_train=np.array(x_train).reshape(-1,1)
y_train=np.array(y_train).reshape(-1,1)

model=LinearRegression()
model. fit(x_train,y_train)

print (model. coef_)
print(model.intercept_)

[[0.1878074]]
[6.94993609]

In [5]:
y_test=np.array(y_test).reshape(-1,1)
y_pred=model.predict(y_test)
print(y_pred)

[[ 9.11793201]
 [ 7.72255295]
 [ 8.09039381]
 [ 9.6625837 ]
 [ 9.08816263]
 [ 9.95285839]
 [ 8.05902252]
 [ 9.50770951]
 [ 9.75592066]
 [ 7.15548917]
 [ 9.87399956]
 [ 9.27481771]
 [ 9.30463301]
 [ 9.65275662]
 [ 8.38954479]
 [ 8.15758429]
 [ 9.42743562]
 [ 7.63889389]
 [ 9.48442847]
 [ 9.5958896 ]
 [ 8.02572223]
 [10.0201986 ]
 [ 8.72413362]
 [ 8.78582592]
 [ 8.4002717 ]
 [10.21225092]
 [ 8.80204176]
 [ 9.95069501]
 [10.20925413]
 [ 8.22860395]
 [ 8.13970003]
 [ 9.49004458]
 [ 8.65688926]
 [ 8.32512428]
 [ 8.55955507]
 [10.17605473]
 [ 7.71559372]
 [ 8.78672349]
 [ 9.51314603]
 [ 9.46966301]
 [10.15373052]
 [ 7.87884844]
 [ 8.51729658]
 [ 7.42906106]
 [10.62752918]
 [ 9.47895672]
 [ 7.9502222 ]
 [ 9.09546942]
 [ 8.79711099]
 [ 7.44850955]
 [ 9.5360875 ]
 [ 9.06642866]
 [ 8.8777584 ]
 [ 9.82346116]
 [ 9.53789128]
 [10.22000306]
 [ 8.71305467]
 [ 8.94028271]
 [ 8.85828505]
 [ 9.66676038]
 [10.45970531]
 [ 9.11114764]
 [ 9.66919197]
 [ 9.76718148]
 [ 8.98041925]
 [10.25873854]
 [ 9.10651667]
 [ 9.61301578]
 [ 9.2345787 ]
 [10.09324291]
 [10.59940203]
 [ 7.79962861]
 [ 8.89892038]
 [ 9.43012872]
 [ 7.9517078 ]
 [ 9.57848652]
 [ 9.53616409]
 [ 8.37573181]
 [ 9.17191144]
 [ 8.05016404]
 [ 7.95601569]
 [10.18284086]
 [ 8.99056163]
 [ 8.0254766 ]
 [ 9.2237973 ]
 [ 8.62829252]
 [10.16778015]
 [ 9.59269519]
 [ 9.95353732]
 [ 8.17382127]
 [ 8.51469442]
 [ 9.16038901]
 [ 9.73424888]
 [ 9.46276296]
 [ 9.65732686]
 [ 8.75603527]
 [ 9.44470771]
 [ 8.70114132]
 [ 9.35624417]
 [ 9.52658585]
 [ 9.34156886]
 [10.46001848]
 [ 7.52602811]
 [ 8.67068506]
 [ 9.06954114]
 [ 9.22212101]
 [ 9.16204364]
 [ 9.68963765]
 [ 9.88782873]
 [ 9.46148551]
 [10.24791884]
 [ 8.74350542]
 [ 8.41791173]
 [ 7.2454377 ]
 [ 8.27221684]
 [ 7.31924962]
 [ 9.54161871]
 [ 8.96495579]
 [ 9.43992484]
 [ 9.5173726 ]
 [ 8.61876699]
 [ 8.78141401]
 [ 7.81974698]
 [ 7.87734011]
 [ 9.73920967]]

In [6]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
import math

print('Mean absolute error:', mean_absolute_error(y_test, y_pred))

print("Mean squared error:", mean_squared_error(y_test, y_pred))
print('variance score:',r2_score(y_test, y_pred))

print('Root Mean Squared Error:',math.sqrt(mean_squared_error(y_test, y_pred)))

Mean absolute error: 3.5148590583133705
Mean squared error: 16.92572743675357
variance score: 0.09377824181351735
Root Mean Squared Error: 4.114088895096163